// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Click struct {
	ID          uuid.UUID
	ShortLinkID uuid.UUID
	IpAddress   string
	Country     string
	Referrer    string
	IsUnique    bool
	UtmSource   string
	UtmMedium   string
	UtmCampaign string
	CreatedAt   time.Time
}

type Device struct {
	ID         uuid.UUID
	ClickID    uuid.UUID
	UserAgent  string
	DeviceType string
	Language   string
	Platform   string
	Resolution string
	Timezone   string
	CreatedAt  time.Time
}

type ShortLink struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Slug        string
	OriginalUrl string
	UtmSource   string
	UtmMedium   string
	UtmCampaign string
	IsActive    sql.NullBool
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
}

type Token struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	RefreshToken string
	CreatedAt    time.Time
	UpdatedAt    sql.NullTime
	LastUsedAt   time.Time
}

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}
